services:
  ethstats-server:
    image: ethstats-server
    build:
      context: docker/ethstats-server
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-lts-trixie}
    hostname: ethstats-server
    environment:
      - WS_SECRET=${WS_SECRET:-asdf}
    command: npm start
    networks:
      besu_network:
        ipv4_address: 192.168.100.100
    ports:
      - "3000:3000"

volumes:
  root_data:

networks:
  besu_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254
