services:
  workspace:
    image: workspace
    build:
      context: docker/workspace
      dockerfile: Dockerfile
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION:-latest}
    hostname: workspace
    networks:
      besu_network:
        ipv4_address: 192.168.100.200
    volumes:
      - ./private:/blockchain
      - root_data:/root

  ethstats-server:
    image: ethstats-server
    build:
      context: docker/ethstats-server
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION:-lts-trixie}
    hostname: ethstats-server
    environment:
      - WS_SECRET=${WS_SECRET:-asdf}
    command: npm start
    networks:
      besu_network:
        ipv4_address: 192.168.100.100
    ports:
      - "3000:3000"

  besu-node1:
    image: hyperledger/besu:${BESU_VERSION:-26.2.0}
    hostname: besu-node1
    volumes:
      - ./private/jwts:/var/lib/besu/jwts
      - ./private/networkFiles:/var/lib/besu/QBFT-Network/networkFiles
      - ./besu:/var/lib/besu/config
      - ./private/node_data/besu-node1:/var/lib/besu/QBFT-Network/Node
    command: --config-file=/var/lib/besu/config/node-config.toml
    networks:
      besu_network:
        ipv4_address: 192.168.100.1
    environment:
      - BESU_NODE_PRIVATE_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key1
      - BESU_ETHSTATS=besu-node1:${WS_SECRET:-asdf}@ethstats-server:3000
      - BESU_RPC_WS_AUTHENTICATION_ENABLED=false
      - BESU_RPC_WS_AUTHENTICATION_JWT_ALGORITHM=RS256
      - BESU_RPC_WS_AUTHENTICATION_JWT_PUBLIC_KEY_FILE="/var/lib/besu/jwts/1/publicRSAKeyOperator1.pem"

  besu-node2:
    image: hyperledger/besu:${BESU_VERSION:-26.2.0}
    hostname: besu-node2
    volumes:
      - ./private/jwts:/var/lib/besu/jwts
      - ./private/networkFiles:/var/lib/besu/QBFT-Network/networkFiles
      - ./besu:/var/lib/besu/config
      - ./private/node_data/besu-node2:/var/lib/besu/QBFT-Network/Node
    command: --config-file=/var/lib/besu/config/node-config.toml
    networks:
      besu_network:
        ipv4_address: 192.168.100.2
    environment:
      - BESU_NODE_PRIVATE_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key2
      - BESU_ETHSTATS=besu-node2:${WS_SECRET:-asdf}@ethstats-server:3000
      - BESU_RPC_WS_AUTHENTICATION_ENABLED=false
      - BESU_RPC_WS_AUTHENTICATION_JWT_ALGORITHM=RS256
      - BESU_RPC_WS_AUTHENTICATION_JWT_PUBLIC_KEY_FILE="/var/lib/besu/jwts/2/publicRSAKeyOperator2.pem"

  besu-node3:
    image: hyperledger/besu:${BESU_VERSION:-26.2.0}
    hostname: besu-node3
    volumes:
      - ./private/jwts:/var/lib/besu/jwts
      - ./private/networkFiles:/var/lib/besu/QBFT-Network/networkFiles
      - ./besu:/var/lib/besu/config
      - ./private/node_data/besu-node3:/var/lib/besu/QBFT-Network/Node
    command: --config-file=/var/lib/besu/config/node-config.toml
    networks:
      besu_network:
        ipv4_address: 192.168.100.3
    environment:
      - BESU_NODE_PRIVATE_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key3
      - BESU_ETHSTATS=besu-node3:${WS_SECRET:-asdf}@ethstats-server:3000
      - BESU_RPC_WS_AUTHENTICATION_ENABLED=false
      - BESU_RPC_WS_AUTHENTICATION_JWT_ALGORITHM=RS256
      - BESU_RPC_WS_AUTHENTICATION_JWT_PUBLIC_KEY_FILE="/var/lib/besu/jwts/3/publicRSAKeyOperator3.pem"

  besu-node4:
    image: hyperledger/besu:${BESU_VERSION:-26.2.0}
    hostname: besu-node4
    volumes:
      - ./private/jwts:/var/lib/besu/jwts
      - ./private/networkFiles:/var/lib/besu/QBFT-Network/networkFiles
      - ./besu:/var/lib/besu/config
      - ./private/node_data/besu-node4:/var/lib/besu/QBFT-Network/Node
    command: --config-file=/var/lib/besu/config/node-config.toml
    networks:
      besu_network:
        ipv4_address: 192.168.100.4
    environment:
      - BESU_NODE_PRIVATE_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key4
      - BESU_ETHSTATS=besu-node4:${WS_SECRET:-asdf}@ethstats-server:3000
      - BESU_RPC_WS_AUTHENTICATION_ENABLED=false
      - BESU_RPC_WS_AUTHENTICATION_JWT_ALGORITHM=RS256
      - BESU_RPC_WS_AUTHENTICATION_JWT_PUBLIC_KEY_FILE="/var/lib/besu/jwts/4/publicRSAKeyOperator4.pem"

  besu-node5:
    image: hyperledger/besu:${BESU_VERSION:-26.2.0}
    hostname: besu-node5
    volumes:
      - ./private/jwts:/var/lib/besu/jwts
      - ./private/networkFiles:/var/lib/besu/QBFT-Network/networkFiles
      - ./besu:/var/lib/besu/config
      - ./private/node_data/besu-node5:/var/lib/besu/QBFT-Network/Node
    command: --config-file=/var/lib/besu/config/node-config.toml
    networks:
      besu_network:
        ipv4_address: 192.168.100.5
    environment:
      - BESU_NODE_PRIVATE_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key5
      - BESU_ETHSTATS=besu-node5:${WS_SECRET:-asdf}@ethstats-server:3000
      - BESU_RPC_WS_AUTHENTICATION_ENABLED=false
      - BESU_RPC_WS_AUTHENTICATION_JWT_ALGORITHM=RS256
      - BESU_RPC_WS_AUTHENTICATION_JWT_PUBLIC_KEY_FILE="/var/lib/besu/jwts/5/publicRSAKeyOperator5.pem"

volumes:
  root_data:

networks:
  besu_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254
