services:
  workspace:
    image: workspace
    build:
      context: docker/workspace
      dockerfile: Dockerfile
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION:-latest}
    hostname: workspace
    networks:
      besu_network:
        ipv4_address: 192.168.100.200
    volumes:
      - ./private:/blockchain
      - root_data:/root
